---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SourcegraphKeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH key pair to access the EC2 instance running Sourcegraph
  SourcegraphSize:
    Type: String
    Description: See docs for more info docs.sourcegraph.com/admin/deploy/machine-images/aws-oneclick
    Default: XS
    AllowedValues:
      - XS
      - S
      - M
      - L
      - XL

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - 
        Label: 
          default: "EC2 Configuration"
        Parameters: 
          - SourcegraphKeyPair
      - 
        Label: 
          default: "Sourcegraph Configuration"
        Parameters: 
          - SourcegraphSize
    ParameterLabels:
      SourcegraphKeyPair:
        default: "SSH Keypair"
      SourcegraphSize:
        default: "Sourcegraph Instance Size"

Resources:
  SourcegraphSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables the ports Sourcegraph requires (22, 80, 443)
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
  SourcegraphInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref SourcegraphKeyPair
      Tags:
      - Key: Name
        Value: Sourcegraph
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - Fn::FindInMap:
          - SizeToType
          - Ref: SourcegraphSize
          - Type
      InstanceType: 
        Fn::FindInMap:
        - InstanceType
        - Ref: SourcegraphSize
        - Instance
      SecurityGroupIds:
        - !Ref SourcegraphSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          export SOURCEGRAPH_SIZE=${SourcegraphSize}
          bash /home/ec2-user/install.sh

Mappings:
  SizeToType:
    XS:
      Type: gp3
    S:
      Type: gp3
    M:
      Type: gp3
    L:
      Type: io2
    XL:
      Type: io2
  InstanceType:
    XS: 
      Instance: m6a.2xlarge
    S: 
      Instance: m6a.4xlarge
    M: 
      Instance: m6a.8xlarge
    L: 
      Instance: m6a.12xlarge
    XL: 
      Instance: m6a.24xlarge
  RegionMap:
    af-south-1:
      io2: ami-0fb856e50d2d3b152
      gp3: ami-0e5fe2d6c7f30e33e
    ap-east-1:
      io2: ami-00eb98fa5290b7d80
      gp3: ami-0278ea55afb78913c
    ap-northeast-1:
      io2: ami-06795469bb7a7870d
      gp3: ami-0df0de75a3fe67083
    ap-northeast-2:
      io2: ami-0ec39e0c5d0944d5d
      gp3: ami-055dc8aa7e20ae2d2
    ap-south-1:
      io2: ami-068f3c12825383c3a
      gp3: ami-0ef969fdba6b51096
    ap-southeast-1:
      io2: ami-059c6be412b6e553e
      gp3: ami-0a14c140526a945a4
    ap-southeast-2:
      io2: ami-06f991bd0c338ac38
      gp3: ami-050770f4a26b582d7
    ap-southeast-3:
      io2: ami-0d5091da3835afaed
      gp3: ami-018d54febaacfa8bd
    ca-central-1:
      io2: ami-021af8e6f3e0376f2
      gp3: ami-0532b3e10b7cbaf51
    eu-central-1:
      io2: ami-007e4f6027b51436c
      gp3: ami-0457e56eaa734221a
    eu-north-1:
      io2: ami-063b0c4a0d1c703ab
      gp3: ami-0de580a2b0e88cfae
    eu-south-1:
      io2: ami-06605fdc07840c54c
      gp3: ami-03e717d6f18aa4b22
    eu-west-1:
      io2: ami-018c9f3eae1da2b29
      gp3: ami-03fb79c8c2a80c6ae
    eu-west-2:
      io2: ami-068af020328ded375
      gp3: ami-06bc9c9ae53277fa6
    eu-west-3:
      io2: ami-01070812c0855e4c3
      gp3: ami-0aaf4555787856a39
    me-central-1:
      io2: ami-00d44f77a63ea27bf
      gp3: ami-0afa1dfe9a4d4ceaf
    me-south-1:
      io2: ami-038187e6674d65a50
      gp3: ami-015381c79d673236c
    sa-east-1:
      io2: ami-0cc84aa4c673ccbb0
      gp3: ami-0157800464415f7b4
    us-east-1:
      io2: ami-0c86fcc2edca9ebd0
      gp3: ami-017d4e697c4ffdaaa
    us-east-2:
      io2: ami-07e00b1fd0460b45a
      gp3: ami-08882d53f560a7e67
    us-west-1:
      io2: ami-0611be37a8e94d2a7
      gp3: ami-07db7f945f85bb14e
    us-west-2:
      io2: ami-0656ec1216ed90b30
      gp3: ami-0d11e8634c489c1a4

Outputs:
  SourcegraphURL:
    Description: URL for your Sourcegraph instance - sign in here!
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - SourcegraphInstance
          - PublicIp
        - ":80"
