---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SourcegraphKeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH key pair to access the EC2 instance running Sourcegraph
  SourcegraphSize:
    Type: String
    Description: See docs for more info docs.sourcegraph.com/admin/deploy/machine-images/aws-oneclick
    Default: XS
    AllowedValues:
      - XS
      - S
      - M
      - L
      - XL

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - 
        Label: 
          default: "EC2 Configuration"
        Parameters: 
          - SourcegraphKeyPair
      - 
        Label: 
          default: "Sourcegraph Configuration"
        Parameters: 
          - SourcegraphSize
    ParameterLabels:
      SourcegraphKeyPair:
        default: "SSH Keypair"
      SourcegraphSize:
        default: "Sourcegraph Instance Size"

Resources:
  SourcegraphSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables the ports Sourcegraph requires (22, 80, 443)
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
  SourcegraphInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref SourcegraphKeyPair
      Tags:
      - Key: Name
        Value: Sourcegraph
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - Fn::FindInMap:
          - SizeToType
          - Ref: SourcegraphSize
          - Type
      InstanceType: 
        Fn::FindInMap:
        - InstanceType
        - Ref: SourcegraphSize
        - Instance
      SecurityGroupIds:
        - !Ref SourcegraphSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          export SOURCEGRAPH_SIZE=${SourcegraphSize}
          bash /home/ec2-user/install.sh

Mappings:
  SizeToType:
    XS:
      Type: gp3
    S:
      Type: gp3
    M:
      Type: gp3
    L:
      Type: io2
    XL:
      Type: io2
  InstanceType:
    XS: 
      Instance: m6a.2xlarge
    S: 
      Instance: m6a.4xlarge
    M: 
      Instance: m6a.8xlarge
    L: 
      Instance: m6a.12xlarge
    XL: 
      Instance: m6a.24xlarge
  RegionMap:
    af-south-1:
      io2: ami-02952310b60eb12b5
      gp3: ami-043d169c300a847c9
    ap-east-1:
      io2: ami-07cea7c69215da056
      gp3: ami-0ac70867cc10664cd
    ap-northeast-1:
      io2: ami-03c5262c921ff5d82
      gp3: ami-09ea1054cbeef8c97
    ap-northeast-2:
      io2: ami-08a86de8136cadf00
      gp3: ami-0d7251f03b367fe46
    ap-south-1:
      io2: ami-0901920dc8ace3b86
      gp3: ami-0dcd9f190e8d999c2
    ap-southeast-1:
      io2: ami-0b1308766a77c3c69
      gp3: ami-0aacf5cd7160093fe
    ap-southeast-2:
      io2: ami-04bd5f741d958dbab
      gp3: ami-0814da41216a7c12d
    ap-southeast-3:
      io2: ami-05b3a08a8372ec46f
      gp3: ami-08785f05a86d1fa46
    ca-central-1:
      io2: ami-011353a3b73eb01da
      gp3: ami-01ed89924f1dbdbf8
    eu-central-1:
      io2: ami-0a6eb334378ac3d6b
      gp3: ami-03301e4def51fae20
    eu-north-1:
      io2: ami-0c957be8329f14883
      gp3: ami-07516634aa8be8481
    eu-south-1:
      io2: ami-0445052ee05b0554e
      gp3: ami-0bf2148224ddc820a
    eu-west-1:
      io2: ami-053f9869218b42cf3
      gp3: ami-07f3ced7f39257ce6
    eu-west-2:
      io2: ami-0e823680fba1ac29e
      gp3: ami-0a32d0f66fe82115a
    eu-west-3:
      io2: ami-0b597d6ac9f77a83f
      gp3: ami-0d851a15194305ab3
    me-central-1:
      io2: ami-03ca02e4512a7a813
      gp3: ami-0dbcdde688c092dc6
    me-south-1:
      io2: ami-0f7c8d48db5409b6e
      gp3: ami-0b73569f7fcf3505a
    sa-east-1:
      io2: ami-083c10595d69f2062
      gp3: ami-00673bd8afb074cce
    us-east-1:
      io2: ami-0d116fc79f6d21b44
      gp3: ami-0d066906c9a411a67
    us-east-2:
      io2: ami-0ed885ad386c6b1ac
      gp3: ami-06cf5a3f7a1f7941c
    us-west-1:
      io2: ami-06e0840cbf6c605dd
      gp3: ami-0c7ebac41676fa8eb
    us-west-2:
      io2: ami-095ee18b9c1b5b45d
      gp3: ami-0e15a85f730ea9b23

Outputs:
  SourcegraphURL:
    Description: URL for your Sourcegraph instance - sign in here!
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - SourcegraphInstance
          - PublicIp
        - ":80"
